### ISSUE TITLE
SSLHandshake failed on Linux platform when SSL cert is not in /usr/local/ssl

### ISSUE THREAD

**Issue by howryu** [Azure/azure-storage-cpp#197]
```
[2018-07-09 10:39:56.664370] [0x00007fffdefb2700] [info]    6185B6C7-BECE-47CF-A23F-138360A88467 : Starting HEAD request to https://2mtpaab7eosfcstage.blob.core.windows.net/tableszz850bfef9-7718-489d-b502-7e377f34ebd9/small_file.csv.gz
[2018-07-09 10:39:57.009000] [0x00007fffed5c9700] [warning] 6185B6C7-BECE-47CF-A23F-138360A88467 : Exception thrown while processing response: Error in SSL handshake
[2018-07-09 10:39:57.009044] [0x00007fffed5c9700] [info]    6185B6C7-BECE-47CF-A23F-138360A88467 : Retrying failed operation, number of retries: 1
[2018-07-09 10:40:00.010356] [0x00007fffeadc5700] [info]    6185B6C7-BECE-47CF-A23F-138360A88467 : Starting HEAD request to https://2mtpaab7eosfcstage.blob.core.windows.net/tableszz850bfef9-7718-489d-b502-7e377f34ebd9/small_file.csv.gz
[2018-07-09 10:40:00.273076] [0x00007ffff43d4700] [warning] 6185B6C7-BECE-47CF-A23F-138360A88467 : Exception thrown while processing response: Error in SSL handshake
[2018-07-09 10:40:00.273108] [0x00007ffff43d4700] [info]    6185B6C7-BECE-47CF-A23F-138360A88467 : Retrying failed operation, number of retries: 2
[2018-07-09 10:40:06.223574] [0x00007fffee9cb700] [info]    6185B6C7-BECE-47CF-A23F-138360A88467 : Starting HEAD request to https://2mtpaab7eosfcstage.blob.core.windows.net/tableszz850bfef9-7718-489d-b502-7e377f34ebd9/small_file.csv.gz
[2018-07-09 10:40:06.504989] [0x00007fffe71bf700] [warning] 6185B6C7-BECE-47CF-A23F-138360A88467 : Exception thrown while processing response: Error in SSL handshake
[2018-07-09 10:40:06.505022] [0x00007fffe71bf700] [info]    6185B6C7-BECE-47CF-A23F-138360A88467 : Retrying failed operation, number of retries: 3
[2018-07-09 10:40:17.494003] [0x00007fffeadc5700] [info]    6185B6C7-BECE-47CF-A23F-138360A88467 : Starting HEAD request to https://2mtpaab7eosfcstage.blob.core.windows.net/tableszz850bfef9-7718-489d-b502-7e377f34ebd9/small_file.csv.gz
[2018-07-09 10:40:17.781027] [0x00007fffec1c7700] [warning] 6185B6C7-BECE-47CF-A23F-138360A88467 : Exception thrown while processing response: Error in SSL handshake
[2018-07-09 10:40:17.781050] [0x00007fffec1c7700] [error]   6185B6C7-BECE-47CF-A23F-138360A88467 : Retry policy did not allow for a retry, so throwing exception: Error in SSL handshake
terminate called after throwing an instance of 'azure::storage::storage_exception'
  what():  Error in SSL handshake
Signal: SIGABRT (Aborted)
```

It seems that SSLHandshake failed. Is there a way to know in detail which steps in handshake failed? I know this error comes from cpprestsdk. Also, I suspect the cacert file is out of date on my local machine. Is there a way to pass down custom cacert pem file down to the cpprest. Since it seem cpprest allows user to pass in custom cacert file. https://github.com/Microsoft/cpprestsdk/issues/542

**Comment by howryu** [comment]
Seems same issue as #156

**Comment by howryu** [comment]
I am pretty sure this is a certificate issue. 
```
#include <cpprest/http_client.h>
#include <cpprest/filestream.h>

using namespace utility;                    // Common utilities like string conversions
using namespace web;                        // Common features like URIs.
using namespace web::http;                  // Common HTTP functionality
using namespace web::http::client;          // HTTP client features
using namespace concurrency::streams;       // Asynchronous streams

int main(int argc, char* argv[])
{
  auto fileStream = std::make_shared<ostream>();

  // Open stream to output file.
  pplx::task<void> requestTask = fstream::open_ostream(U("results.html")).then([=](ostream outFile)
    {
       *fileStream = outFile;

        http_client_config config;
        config.set_ssl_context_callback([](boost::asio::ssl::context& context)-> void{
            context.load_verify_file(std::string("/home/hyu/Snowflake/git/libsnowflakeclient/cacert.pem"));
        });

       // Create http_client to send the request.
       http_client client(U("https://www.bing.com/"), config);

       // Build request URI and start the request.
       uri_builder builder(U("/search"));
       builder.append_query(U("q"), U("cpprestsdk github"));
      return client.request(methods::GET, builder.to_string());
    })

      // Handle response headers arriving.
    .then([=](http_response response)
          {
              printf("Received response status code:%u\n", response.status_code());

              // Write response body into the file.
              return response.body().read_to_end(fileStream->streambuf());
          })

      // Close the file stream.
    .then([=](size_t)
          {
              return fileStream->close();
          });

  // Wait for all the outstanding I/O to complete and handle any exceptions
  try
  {
    requestTask.wait();
  }
  catch (const std::exception &e)
  {
    printf("Error exception:%s\n", e.what());
  }

  return 0;
}```
I copied a simple file, which is just accessing some websites using cpprestsdk httpclient. By default, it failed. However, after I adding following lines
```
       http_client_config config;
        config.set_ssl_context_callback([](boost::asio::ssl::context& context)-> void{
            context.load_verify_file(std::string("/home/hyu/Snowflake/git/libsnowflakeclient/cacert.pem"));
        });

       // Create http_client to send the request.
       http_client client(U("https://www.bing.com/"), config);
```
It succeed.

**Comment by katmsft** [comment]
Thanks for reporting the issue and provide such detailed information. It seems that we do not expose the interface for Linux users to specify the SSL cert location like CPPRest did. This issue is acknowledged and will be fixed in the next release.

**Comment by howryu** [comment]
Thanks! So I assume the next release is 5.1.0, which targets for end of July, right? Since I am waiting for another fix as well (#151 )

**Comment by howryu** [comment]
BTW, is this issue resolved in latest v5.1.0 release?

**Comment by katmsft** [comment]
The issue is not yet fixed because it should not be a blocking issue for our customer, and we think we should be cautious about setting the SSL cert manually. Our plan was to support this in 5.1.0 but it gets postponed for further evaluation.

**Comment by Dyutighosh** [comment]
Hi @howryu & @katmsft  ,
I am using cpprestsdk 2.10.3 along with boost 1.62 and openssl 1.1.0 for building the latest blob-storage sdk in Linux. And getting the same issue mentioned above. (I.e. Error in SSL handshake) So till this issue is resolved, is there any other way round for successfully testing my sample application? 

Thank you..

**Comment by howryu** [comment]
@Dyutighosh I don't have workaround. For me, I statically link OpenSSL, this ssl is determined at compile time. If you are using dynamic linking, you probably can look at openssl install directory on your local machine.

**Comment by katmsft** [comment]
This issue is addressed in 5.1.1, please check it out!

**Comment by Dyutighosh** [comment]
@katmsft  I tried with the latest version of blob storage sdk (5.1.1) But getting the same error. This is what i am doing:
azure::storage::operation_context context;
context.set_ssl_context_callback([](boost::asio::ssl::context& context)-> void {
context.load_verify_file(string("~/cacert.pem"));
cout << "Exception in ssl callback................" <<endl; });

Error: Error in SSL handshake

Thereafter I tried to build the samples , during make I am getting the following errors:
[ 86%] Linking CXX executable ../../Binaries/samplesblobs
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlTextReaderMoveToFirstAttribute'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlNewNs'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlFreeTextReader'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlSetNsProp'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlReaderForMemory'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlSetNs'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlNewDocNode'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlNewDoc'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlFree'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlSetProp'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlTextReaderNodeType'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlDocSetRootElement'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlFreeDoc'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlSearchNs'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlTextReaderRead'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlTextReaderValue'
../../Binaries/libazurestorage.so.5.1: undefined reference to `__xmlIndentTreeOutput'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlTextReaderLocalName'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlDocDumpFormatMemoryEnc'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlTextReaderMoveToNextAttribute'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlNewNode'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlTextReaderIsEmptyElement'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlNewText'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlNodeSetContent'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlAddChild'
../../Binaries/libazurestorage.so.5.1: undefined reference to `xmlDocGetRootElement'
collect2: error: ld returned 1 exit status
samples/BlobsGettingStarted/CMakeFiles/samplesblobs.dir/build.make:111: recipe for target 'Binaries/samplesblobs' failed
make[2]: *** [Binaries/samplesblobs] Error 1
CMakeFiles/Makefile2:229: recipe for target 'samples/BlobsGettingStarted/CMakeFiles/samplesblobs.dir/all' failed
make[1]: *** [samples/BlobsGettingStarted/CMakeFiles/samplesblobs.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Kindly help me out on this...

**Comment by katmsft** [comment]
@Dyutighosh Thanks for reporting the issues.

1. Can you please ensure that the SSL cert can be used solely with Casablanca? This Client Library does not modify the settings when user tried to set them. It merely pass the option down to Casablanca and let it handle the settings.

2. It seems that the sample can compile all right, but an error is reported when linking the executable. Can you please confirm that the libxml2 is installed on this machine, since all the undefined reference are from libxml2.

**Comment by katmsft** [comment]
@Dyutighosh can you open an issue in [cpprest's repo](https://github.com/Microsoft/cpprestsdk) for the failure? It seems that cpprest cannot handle this setting.
Glad to see that the linking issue is resolved.

**Comment by katmsft** [comment]
Hi, I have opened an issue in cpprestsdk's repo: https://github.com/Microsoft/cpprestsdk/issues/929

This way you can track the issue more clearly. And we are closing this issue since this is no longer an issue that is solvable in this SDK. Feel free to contact us again or reopen the issue if needed.

**Comment by crusader-mike** [comment]
See: https://github.com/microsoft/cpprestsdk/issues/929#issuecomment-635587905

**Comment by katmsft** [comment]
Hi,
The issue is already resolved for non-Windows platforms by exposing `set_ssl_context_callback`.

**Comment by crusader-mike** [comment]
@katmsft I know, I spent at least a day figuring out this (or similar issue). Thought I'd leave a trace for others.
